#!/bin/bash
#!/usr/bin/env bash

upload_file () {
    source=$1
    dest=$2

    # if [ ! -z $3 ]
    # then
    #     usrExtension=$3
    # fi
    # echo 'upload_file called' $source $dest $usrExtension

    if [ -d $source ] 
    then
        src=$source'/*'
        for f in $src
        do
            upload_file $f $dest
        done
    else
        if [ ${#callerTypes} -ge 1 ]; 
        then 
            destFile="${clientId}${callerTypes}.mp3"
            # destFile=${source/.mp3/$usrExtension'.mp3'};
        else 
            destFile="$clientId-all.mp3"
            # destFile=${source/.mp3/'-all.mp3'};
        fi 
        destFile=${destFile/$sourceDirectory/''}
        # aws s3 cp $source $dest$destFile --dryrun --exclude "*" --include "*.mp3" --recursive --profile marklar # aws for folder upload
        aws s3 cp $source $dest$destFile  --dryrun
    fi
}

callerTypes=''
sourceDirectory=''
clientId=''
lang='en'
while getopts ":s:u:c:l:" option
do
    case $option in
            s) 
                #source File or Directory name
                src=${OPTARG}
                SOURCE="$src"
                ;;
            u)
                #array of specific user list for prompt
                n=0 ;for i in ${OPTARG}; do callerTypes=$callerTypes'-'$i; let n++; done ;
                ;;
            c)
                # get the clientid
                clientId=${OPTARG}
                ;;
            l)
                #get the audio lang
                lang=${OPTARG}
                ;;

    esac
done

if [ ! -z $clientId ]
then
    destFolder="s3://marklar/custom/prompts/client/$clientId/$lang/"
    # echo 'dest value is set to' $destFolder
fi


# check if source is Directory or File
if [ -d $SOURCE ] 
then
    sourceDirectory=$SOURCE
    SOURCE=$SOURCE'*'
    for f in $SOURCE; 
    do
        sourceFile="$(echo -e "${f}" | tr -d '[:space:]')" #remove the white spaces from file name
        upload_file $sourceFile $destFolder
    done
else
    upload_file $SOURCE $destFolder
fi

