#!/bin/bash
#!/usr/bin/env bash


#set defaults and constants
callerTypes=''
sourceDirectory=''
clientId=''
lang='en'

LOCAL_DIR="custom/prompts/client/"
CALLER_TYPE_ARRAYS=( councilmember auditor client )

upload_file () {
    source=$1
    dest=$2

    s3DestFolder="s3://marklar/$dest"
    localFolder=$LOCAL_DIR$clientId
    fileForAllName="$clientId-all.mp3"
    if [ -d $source ] 
    then
        src=$source'/*'
        for f in $src
        do
            upload_file $f $dest
        done
    else
        #check for local directory, create if doesnt exist
        if [ ! -d "$localFolder" ];
        then
            mkdir $localFolder
        fi

        if [ ! -d "$localFolder/$lang" ];
        then
            mkdir "$localFolder/$lang"
        fi

        githubFolderName="$localFolder/$lang/"
        if [ ${#callerTypes} -ge 1 ]; 
        then 
            callerTypes=$(echo "${callerTypes}" | tr '[:upper:]' '[:lower:]') #convert to lower case

            destFile="${clientId}${callerTypes}.mp3"
            
            if [  -f $githubFolderName$fileForAllName ]; #if file for all exists delete and rename to remaining caller types
            then
                fileName=''
                #rename -all.mp3 file to specific caller types
                for i in "${CALLER_TYPE_ARRAYS[@]}"; 
                do 
                    if [[ $callerTypes != *$i* ]];
                    then
                        fileName=$fileName'-'$i
                    fi 
                done ;
                mv $githubFolderName$fileForAllName "$githubFolderName$clientId$fileName.mp3"
            fi
        else 
            destFile=fileForAllName
        fi 


        #copy file to local folder and push it to gitgub
        cp $source "$githubFolderName$destFile"

        git add "$githubFolderName"
        # git commit -m "adding $destFile to $dest"
        #git push origin master

        # aws s3 cp $source $dest$destFile --dryrun --exclude "*" --include "*.mp3" --recursive --profile marklar # aws for folder upload
        aws s3 cp $source "s3://marklar/$dest$destFile"  --dryrun
    fi
}


#get options
while getopts ":s:u:c:l:" option
do
    case $option in
            s) 
                #source File or Directory name
                src=${OPTARG}
                SOURCE="$src"
                ;;
            u)
                #array of specific user list for prompt
                n=0 ;for i in ${OPTARG}; do callerTypes=$callerTypes'-'$i; let n++; done ;
                ;;
            c)
                # get the clientid
                clientId=${OPTARG}
                ;;
            l)
                #get the audio lang
                lang=${OPTARG}
                ;;

    esac
done

#create destination folders
if [ ! -z $clientId ]
then
    destFolder="custom/prompts/client/$clientId/$lang/"
fi


# check if source is Directory or File
if [ -d $SOURCE ] 
then
    sourceDirectory=$SOURCE
    SOURCE=$SOURCE'*'
    for f in $SOURCE; 
    do
        sourceFile="$(echo -e "${f}" | tr -d '[:space:]')" #remove the white spaces from file name
        upload_file $sourceFile $destFolder
    done
else
    upload_file $SOURCE $destFolder
fi

